import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/common/main/Header";
import { SideMenu } from "@/components/common/main/SideMenu";
import { MainContainer } from "@/components/common/main/MainContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="h-screen bg-gray-100 text-gray-900"
      >
        <Header />
        <div className="flex h-full">
          <SideMenu />
          <MainContainer>
            {children}
          </MainContainer>
        </div>
      </body>
    </html>
  );
}
